import { Model } from "./model";
import { PurchaseOrderDetail } from "./purchase_order_detail";
import { Stage } from "./stage";
import { CustomerSupplier } from "./supplier_customer";
import { DropDownModel } from "./drop_down";
import { SelectItem } from "../components/common/selectitem";
import { Inventory } from "./inventory";

export class PurchaseOrder extends Model{
    poCode:string;
    trxnDate:Date;
    estDeliveryDate:Date;
    totalAmount:number;
    totalTaxAmount:number;
    poType:string;
    suppId:number;
    suppName:string;
    pods:PurchaseOrderDetail[];
    nDraft:number;
    nAwApproval:number;
    nAwPayment:number;
    nPaid:number;
    nOverdue:number;
    nDraftQ:number;
    nAwApprovalQ:number;
    nAwPaymentQ:number;
    nOverdueQ:number;
    nPaidQ:number;
    referrence:string;
    selected:boolean;
    stage:Stage;
    purchaseIds:number[];
    custSupps:SelectItem[];
    inventories:SelectItem[];
    inventories2:Inventory[];
    coas:SelectItem[];
    taxes:SelectItem[];
    soType:string;
    totalAmtDraft:number;
    totalAmtAwApproval:number;
    totalAmtAwPayment:number;
    totalAmtPaid:number;
    totalAmtDraftQ:number;
    totalAmtAwApprovalQ:number;
    totalAmtAwPaymentQ:number;
    totalAmtPaidQ:number;
}
